// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from '@prismicio/types'
import type * as prismic from '@prismicio/client'

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType]
}
/** Content for Product documents */
interface ProductDocumentData {
  /**
   * Name field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField
}
/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<Simplify<ProductDocumentData>, 'product', Lang>
export type AllDocumentTypes = ProductDocument
/**
 * Primary content in PublicHeader → Primary
 *
 */
interface PublicHeaderSliceDefaultPrimary {
  /**
   * Title field in *PublicHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: public_header.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.TitleField
  /**
   * Description field in *PublicHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: public_header.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField
}
/**
 * Default variation for PublicHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PublicHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PublicHeaderSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<PublicHeaderSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *PublicHeader*
 *
 */
type PublicHeaderSliceVariation = PublicHeaderSliceDefault
/**
 * PublicHeader Shared Slice
 *
 * - **API ID**: `public_header`
 * - **Description**: `PublicHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PublicHeaderSlice = prismicT.SharedSlice<
  'public_header',
  PublicHeaderSliceVariation
>
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }
  namespace Content {
    export type {
      ProductDocumentData,
      ProductDocument,
      AllDocumentTypes,
      PublicHeaderSliceDefaultPrimary,
      PublicHeaderSliceDefault,
      PublicHeaderSliceVariation,
      PublicHeaderSlice,
    }
  }
}
